# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/minitpu/minitpu.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==minitpu || ORIG_REF_NAME==minitpu} -quiet] -quiet

# IP: bd/minitpu/ip/minitpu_zynq_ps_0/minitpu_zynq_ps_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==minitpu_zynq_ps_0 || ORIG_REF_NAME==minitpu_zynq_ps_0} -quiet] -quiet

# IP: bd/minitpu/ip/minitpu_proc_sys_reset_0_0/minitpu_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==minitpu_proc_sys_reset_0_0 || ORIG_REF_NAME==minitpu_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/minitpu/ip/minitpu_axi_dma_0_0/minitpu_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==minitpu_axi_dma_0_0 || ORIG_REF_NAME==minitpu_axi_dma_0_0} -quiet] -quiet

# IP: bd/minitpu/ip/minitpu_tpu_0_0/minitpu_tpu_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==minitpu_tpu_0_0 || ORIG_REF_NAME==minitpu_tpu_0_0} -quiet] -quiet

# IP: bd/minitpu/ip/minitpu_xbar_0/minitpu_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==minitpu_xbar_0 || ORIG_REF_NAME==minitpu_xbar_0} -quiet] -quiet

# IP: bd/minitpu/ip/minitpu_auto_pc_0/minitpu_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==minitpu_auto_pc_0 || ORIG_REF_NAME==minitpu_auto_pc_0} -quiet] -quiet

# IP: bd/minitpu/ip/minitpu_axi_interconnect_0_0/minitpu_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==minitpu_axi_interconnect_0_0 || ORIG_REF_NAME==minitpu_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/minitpu/ip/minitpu_axi_smc_0/minitpu_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==minitpu_axi_smc_0 || ORIG_REF_NAME==minitpu_axi_smc_0} -quiet] -quiet

# XDC: /home/mss464/minitpu/tpu/ultra96-v2/output/tpu_system/tpu_system.gen/sources_1/bd/minitpu/minitpu_ooc.xdc
