# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/mss464/minitpu/tpu/ultra96-v2/output/tpu_system/tpu_system.srcs/sources_1/bd/minitpu/ip/minitpu_xbar_0/minitpu_xbar_0.xci
# IP: The module: 'minitpu_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mss464/minitpu/tpu/ultra96-v2/output/tpu_system/tpu_system.gen/sources_1/bd/minitpu/ip/minitpu_xbar_0/minitpu_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'minitpu_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/mss464/minitpu/tpu/ultra96-v2/output/tpu_system/tpu_system.srcs/sources_1/bd/minitpu/ip/minitpu_xbar_0/minitpu_xbar_0.xci
# IP: The module: 'minitpu_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mss464/minitpu/tpu/ultra96-v2/output/tpu_system/tpu_system.gen/sources_1/bd/minitpu/ip/minitpu_xbar_0/minitpu_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'minitpu_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
