# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/mss464/minitpu/tpu/ultra96-v2/output/tpu_system/tpu_system.srcs/sources_1/bd/minitpu/ip/minitpu_tpu_0_0/minitpu_tpu_0_0.xci
# IP: The module: 'minitpu_tpu_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/mss464/minitpu/tpu/ultra96-v2/output/tpu_system/tpu_system.gen/sources_1/bd/minitpu/ip/minitpu_tpu_0_0/src/blk_mem_gen_1/blk_mem_gen_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_1 || ORIG_REF_NAME==blk_mem_gen_1} -quiet] -quiet

# XDC: /home/mss464/minitpu/tpu/ultra96-v2/output/tpu_system/tpu_system.gen/sources_1/bd/minitpu/ip/minitpu_tpu_0_0/src/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc

# IP: /home/mss464/minitpu/tpu/ultra96-v2/output/tpu_system/tpu_system.srcs/sources_1/bd/minitpu/ip/minitpu_tpu_0_0/minitpu_tpu_0_0.xci
# IP: The module: 'minitpu_tpu_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/mss464/minitpu/tpu/ultra96-v2/output/tpu_system/tpu_system.gen/sources_1/bd/minitpu/ip/minitpu_tpu_0_0/src/blk_mem_gen_1/blk_mem_gen_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_1 || ORIG_REF_NAME==blk_mem_gen_1} -quiet] -quiet

# XDC: /home/mss464/minitpu/tpu/ultra96-v2/output/tpu_system/tpu_system.gen/sources_1/bd/minitpu/ip/minitpu_tpu_0_0/src/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc
